spring:
  application:
    name: hue-manager

  datasource:
    url: jdbc:mysql://awseb-e-s9ggiypwnn-stack-awsebrdsdatabase-teoirfbyrdzo.c5c8sm6i069x.ap-northeast-2.rds.amazonaws.com/hue_manager
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql:
    init:
      mode: always

jwt:
  token:
    secret: ${JWT_SECRET}
    expired: 86400000 # 24시간

springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    default-models-expand-depth: 2
    default-model-expand-depth: 2
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/**